### ISSUE TITLE
There's something wrong with `add_samples` and dimensions

### ISSUE THREAD

**Issue by Fuuzetsu** [nestordemeure/friedrich#35]
It appears that `add_samples` under some unknown-to-me conditions will panic if we're adding samples. For example, I wrote the following program to demonstrate this and it fails to add even a single sample:

```rust
use friedrich::gaussian_process::GaussianProcess;
use rand::Rng;
use std::ops::Neg;

/// Negated x^2, maximum at 0.
fn objective(x: f64) -> f64 {
    x.powi(2).neg()
}

fn main() {
    // The bound for the parameter.
    let bound = -0.5..=0.5;

    const STARTING_SAMPLES: usize = 10;

    let mut rng = rand::thread_rng();
    // Generate  random points. Note that the input dimension 1, singleton
    // vector.
    let (training_inputs, training_outputs): (Vec<_>, Vec<_>) = (0..STARTING_SAMPLES)
        .map(|_| {
            let x = rng.gen_range(bound.clone());
            let y = objective(x);
            (vec![x], y)
        })
        .unzip();

    // Make the GP and train it on the input data.
    let gp = GaussianProcess::default(training_inputs, training_outputs);

    // Let's see what the model thinks about some point just to prove that it
    // works.
    const SAMPLE_POINT: f64 = 0.1;
    let (mean, variance) = gp.predict_mean_variance(&vec![SAMPLE_POINT]);
    println!(
        "At {} the model has mean of {} and variance of {}",
        SAMPLE_POINT, mean, variance
    );

    // We put the GaussianProcess in a Mutex so that we can make it unwind-safe
    // and catch the panic while reporting how many parameters we managed to
    // add. This doesn't matter for reproducer, you can happily remove this and
    // exhibit the same behaviour.
    let gp = std::sync::Mutex::new(gp);

    // Now that we saw the model work, let's feed it with more data. Note that
    // the dimension provided is still 1D just as expected.
    for param_index in 1..=1_000_000 {
        let x = rng.gen_range(bound.clone());
        let y = objective(x);
        let r =
            std::panic::catch_unwind(|| gp.lock().unwrap().add_samples(&vec![vec![x]], &vec![y]));
        if let Err(e) = r {
            eprintln!(
                "Upon trying to add sample number {}, the GP panicked",
                param_index
            );
            std::panic::resume_unwind(e)
        }
    }
}
```

```console
[nix-develop]$ RUST_BACKTRACE=1 cargo run --release
   Compiling add-data-repro v0.1.0 (/tmp/add-data-repro)
    Finished release [optimized] target(s) in 0.85s
     Running `target/release/add-data-repro`
At 0.1 the model has mean of -0.009955006193071131 and variance of 0.0000007796364186220262
thread 'main' panicked at 'Unable to copy from a matrix with a different shape.', /home/shana/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.23.2/src/base/matrix.rs:1036:9
stack backtrace:
   0: std::panicking::begin_panic
   1: friedrich::algebra::extendable_matrix::EMatrix::add_rows
   2: friedrich::gaussian_process::GaussianProcess<KernelType,PriorType>::add_samples
   3: std::panicking::try
   4: add_data_repro::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Upon trying to add sample number 1, the GP panicked
```

I then realised the main page in the documentation has an example where it's being used. That works. However, I only need to make a minor change to get it to be broken.

Here's the original, working program from the documentation
```rust
fn main() {
    // trains a gaussian process on a dataset of one dimension vectors
    let training_inputs = vec![vec![0.8], vec![1.2], vec![3.8], vec![4.2]];
    let training_outputs = vec![3.0, 4.0, -2.0, -2.0];
    let mut gp = GaussianProcess::default(training_inputs, training_outputs);

    // predicts the mean and variance of a single point
    let input = vec![1.];
    let mean = gp.predict(&input);
    let var = gp.predict_variance(&input);
    println!("prediction: {} ± {}", mean, var.sqrt());

    // makes several prediction
    let inputs = vec![vec![1.0], vec![2.0], vec![3.0]];
    let outputs = gp.predict(&inputs);
    println!("predictions: {:?}", outputs);

    // updates the model
    let additional_inputs = vec![vec![0.], vec![1.], vec![2.], vec![5.]];
    let additional_outputs = vec![2.0, 3.0, -1.0, -2.0];

    gp.add_samples(&additional_inputs, &additional_outputs);
}
```

```console
     Running `target/release/add-data-repro`
prediction: 3.549031440883161 ± 0.2334545603435294
predictions: [3.549031440883161, 3.133998799657853, -0.26002479387497734]
```

but then I change `additional_inputs` and `additional_outputs` to only add a single new sample. Note that the dimensions are still correct.

```rust
    let additional_inputs = vec![vec![0.]];
    let additional_outputs = vec![2.0];
```

```console
     Running `target/release/add-data-repro`
prediction: 3.549031440883161 ± 0.2334545603435294
predictions: [3.549031440883161, 3.133998799657853, -0.26002479387497734]
thread 'main' panicked at 'Unable to copy from a matrix with a different shape.', /home/shana/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.23.2/src/base/matrix.rs:1036:9
stack backtrace:
   0: std::panicking::begin_panic
   1: friedrich::algebra::extendable_matrix::EMatrix::add_rows
   2: friedrich::gaussian_process::GaussianProcess<KernelType,PriorType>::add_samples
   3: add_data_repro::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

This is not a huge problem for us because we retrain the model on every single new sample we add (for us, it's about 6 hours to get a sample so few seconds or even minutes retraining the model doesn't matter currently).

But it seems like there's a bug here that makes `add_samples` somewhat unusable.

On real data that I was testing with, this issue didn't always occur on the very first `add_samples` either, sometimes it managed to actually add a few and only panic on a fourth or fifth and so on.

**Comment by nestordemeure** [comment]
Well spotted, I will investigate when I have a bit of time.

**Comment by nestordemeure** [comment]
This as been fixed as per the latest commit.
